name: GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"   # каждый день в 00:00 UTC
  workflow_dispatch:        # + возможность запустить вручную
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate images
        uses: jstrieb/github-stats@master
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
